version: "3"

services:
  node_one:
    image: raft-trading-server:latest
    container_name: node_one
    ports:
      # HOST:CONTAINER
      - "4001:4000"
      - "6001:6000"
    environment:
      ID: "1"
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      default:
        ipv4_address: 172.20.0.4

  node_two:
    image: raft-trading-server:latest
    container_name: node_two
    ports:
      - "4002:4000"
      - "6002:6000"
    environment:
      ID: "2"
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      default:
        ipv4_address: 172.20.0.2

  node_three:
    image: raft-trading-server:latest
    container_name: node_three
    ports:
      - "4003:4000"
      - "6003:6000"
    environment:
      ID: "3"
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      default:
        ipv4_address: 172.20.0.3

  envoy_service:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    ports:
      - "8000:8000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml


networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
