// source: raft.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.AppendEntriesRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.LogEntry');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AppendEntriesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.AppendEntriesRequest.repeatedFields_, null);
};
goog.inherits(proto.AppendEntriesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.AppendEntriesRequest.displayName = 'proto.AppendEntriesRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.AppendEntriesRequest.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AppendEntriesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.AppendEntriesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AppendEntriesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AppendEntriesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    currentTerm: jspb.Message.getFieldWithDefault(msg, 1, 0),
    leaderId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    leaderCommitIndex: jspb.Message.getFieldWithDefault(msg, 3, 0),
    prevLogIndex: jspb.Message.getFieldWithDefault(msg, 4, 0),
    prevLogTerm: jspb.Message.getFieldWithDefault(msg, 5, 0),
    entriesList: jspb.Message.toObjectList(msg.getEntriesList(),
    proto.LogEntry.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AppendEntriesRequest}
 */
proto.AppendEntriesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AppendEntriesRequest;
  return proto.AppendEntriesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AppendEntriesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AppendEntriesRequest}
 */
proto.AppendEntriesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCurrentTerm(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLeaderId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLeaderCommitIndex(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setPrevLogIndex(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setPrevLogTerm(value);
      break;
    case 6:
      var value = new proto.LogEntry;
      reader.readMessage(value,proto.LogEntry.deserializeBinaryFromReader);
      msg.addEntries(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AppendEntriesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AppendEntriesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AppendEntriesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AppendEntriesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCurrentTerm();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getLeaderId();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getLeaderCommitIndex();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getPrevLogIndex();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getPrevLogTerm();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getEntriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.LogEntry.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint64 current_term = 1;
 * @return {number}
 */
proto.AppendEntriesRequest.prototype.getCurrentTerm = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.AppendEntriesRequest} returns this
 */
proto.AppendEntriesRequest.prototype.setCurrentTerm = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 leader_id = 2;
 * @return {number}
 */
proto.AppendEntriesRequest.prototype.getLeaderId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.AppendEntriesRequest} returns this
 */
proto.AppendEntriesRequest.prototype.setLeaderId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 leader_commit_index = 3;
 * @return {number}
 */
proto.AppendEntriesRequest.prototype.getLeaderCommitIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.AppendEntriesRequest} returns this
 */
proto.AppendEntriesRequest.prototype.setLeaderCommitIndex = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint64 prev_log_index = 4;
 * @return {number}
 */
proto.AppendEntriesRequest.prototype.getPrevLogIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.AppendEntriesRequest} returns this
 */
proto.AppendEntriesRequest.prototype.setPrevLogIndex = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint64 prev_log_term = 5;
 * @return {number}
 */
proto.AppendEntriesRequest.prototype.getPrevLogTerm = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.AppendEntriesRequest} returns this
 */
proto.AppendEntriesRequest.prototype.setPrevLogTerm = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * repeated LogEntry entries = 6;
 * @return {!Array<!proto.LogEntry>}
 */
proto.AppendEntriesRequest.prototype.getEntriesList = function() {
  return /** @type{!Array<!proto.LogEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.LogEntry, 6));
};


/**
 * @param {!Array<!proto.LogEntry>} value
 * @return {!proto.AppendEntriesRequest} returns this
*/
proto.AppendEntriesRequest.prototype.setEntriesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.LogEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.LogEntry}
 */
proto.AppendEntriesRequest.prototype.addEntries = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.LogEntry, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.AppendEntriesRequest} returns this
 */
proto.AppendEntriesRequest.prototype.clearEntriesList = function() {
  return this.setEntriesList([]);
};


