// source: raft.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.ClientAction');
goog.provide('proto.ClientAction.ActionCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.BuyRequest');
goog.require('proto.SellRequest');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ClientAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.ClientAction.oneofGroups_);
};
goog.inherits(proto.ClientAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ClientAction.displayName = 'proto.ClientAction';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.ClientAction.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.ClientAction.ActionCase = {
  ACTION_NOT_SET: 0,
  BUY_REQUEST: 2,
  SELL_REQUEST: 3
};

/**
 * @return {proto.ClientAction.ActionCase}
 */
proto.ClientAction.prototype.getActionCase = function() {
  return /** @type {proto.ClientAction.ActionCase} */(jspb.Message.computeOneofCase(this, proto.ClientAction.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ClientAction.prototype.toObject = function(opt_includeInstance) {
  return proto.ClientAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ClientAction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ClientAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    buyRequest: (f = msg.getBuyRequest()) && proto.BuyRequest.toObject(includeInstance, f),
    sellRequest: (f = msg.getSellRequest()) && proto.SellRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ClientAction}
 */
proto.ClientAction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ClientAction;
  return proto.ClientAction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ClientAction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ClientAction}
 */
proto.ClientAction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new proto.BuyRequest;
      reader.readMessage(value,proto.BuyRequest.deserializeBinaryFromReader);
      msg.setBuyRequest(value);
      break;
    case 3:
      var value = new proto.SellRequest;
      reader.readMessage(value,proto.SellRequest.deserializeBinaryFromReader);
      msg.setSellRequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ClientAction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ClientAction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ClientAction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ClientAction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBuyRequest();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.BuyRequest.serializeBinaryToWriter
    );
  }
  f = message.getSellRequest();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.SellRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional BuyRequest buy_request = 2;
 * @return {?proto.BuyRequest}
 */
proto.ClientAction.prototype.getBuyRequest = function() {
  return /** @type{?proto.BuyRequest} */ (
    jspb.Message.getWrapperField(this, proto.BuyRequest, 2));
};


/**
 * @param {?proto.BuyRequest|undefined} value
 * @return {!proto.ClientAction} returns this
*/
proto.ClientAction.prototype.setBuyRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.ClientAction.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ClientAction} returns this
 */
proto.ClientAction.prototype.clearBuyRequest = function() {
  return this.setBuyRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ClientAction.prototype.hasBuyRequest = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional SellRequest sell_request = 3;
 * @return {?proto.SellRequest}
 */
proto.ClientAction.prototype.getSellRequest = function() {
  return /** @type{?proto.SellRequest} */ (
    jspb.Message.getWrapperField(this, proto.SellRequest, 3));
};


/**
 * @param {?proto.SellRequest|undefined} value
 * @return {!proto.ClientAction} returns this
*/
proto.ClientAction.prototype.setSellRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.ClientAction.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ClientAction} returns this
 */
proto.ClientAction.prototype.clearSellRequest = function() {
  return this.setSellRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ClientAction.prototype.hasSellRequest = function() {
  return jspb.Message.getField(this, 3) != null;
};


